spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = ""
name = "webhook-consumer"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "webhook-consumer"

[component.webhook-consumer]
source = "composed.wasm"
key_value_stores = ["default"]

[component.webhook-consumer.build]
command = "componentize-py -w spin-http componentize app -o app.wasm"
watch = ["*.py", "requirements.txt"]
